Hospital/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hospital.Controllers
{
    public class ConsultaController : Controller
    {
        // GET: Consulta
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hospital/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hospital.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hospital/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult obtenerDoctor(int id = 0)
        {
            Entities model = new Entities();
            var dato = (from d in model.DOCTOR where d.ID == id select d).First();
            return Json(dato);
        }

        public ActionResult obtenerDoctorEspecialidades(int id = 0)
        {
            Entities model = new Entities();
            var datos = (from de in model.DOCTOR_ESPECIALIDAD join e in model.ESPECIALIDAD on de.ID_ESPECIALIDAD equals e.ID where de.ID_DOCTOR == id && de.VISIBLE == true select new { ID = de.ID, ID_DOCTOR = de.ID_DOCTOR, ID_ESPECIALIDAD = de.ID_ESPECIALIDAD, NOMBRE = e.NOMBRE, VISIBLE = de.VISIBLE }).ToList();
            return Json(datos);
        }

        public ActionResult obtenerDoctores(string nombre = "", string apellido = "", string sexo = "0", int especialidad = 0)
        {
            Entities model = new Entities();
            List<DOCTOR> datos = new List<DOCTOR>();
            if (nombre == "" && apellido == "" && sexo == "0" && especialidad == 0)
            {
                datos = (from d in model.DOCTOR where d.VISIBLE == true select d).ToList();
            }
            else
            {
                if (nombre != "")
                {
                    datos = (from d in model.DOCTOR where d.NOMBRE.Contains(nombre) && d.VISIBLE == true select d).ToList();
                }
                if (apellido != "")
                {
                    if (datos.Count == 0)
                    {
                        datos = (from d in model.DOCTOR where d.NOMBRE.Contains(apellido) && d.VISIBLE == true select d).ToList();
                    }
                    else
                    {
                        datos = datos.Where(doctor => doctor.APELLIDO.Contains(apellido)).ToList();
                    }
                }
                if (sexo != "0")
                {
                    if (datos.Count == 0)
                    {
                        datos = (from d in model.DOCTOR where d.SEXO == sexo && d.VISIBLE == true select d).ToList();
                    }
                    else
                    {
                        datos = datos.Where(doctor => doctor.SEXO == sexo).ToList();
                    }
                }
                if (especialidad != 0)
                {
                    if (datos.Count == 0)
                    {

                        datos = (from de in model.DOCTOR_ESPECIALIDAD join doctor in model.DOCTOR on de.ID_DOCTOR equals doctor.ID where de.ID_ESPECIALIDAD == especialidad select doctor).ToList();
                    }
                    else
                    {
                        datos = (from de in model.DOCTOR_ESPECIALIDAD join doctor in datos on de.ID_DOCTOR equals doctor.ID where de.ID_ESPECIALIDAD == especialidad select doctor).ToList();
                    }
                }
            }
            return Json(datos);

        }

        public ActionResult obtenerEspecialidades(string nombre)
        {
            Entities model = new Entities();
            List<ESPECIALIDAD> datos = new List<ESPECIALIDAD>();
            if (nombre == "")
            {
                datos = (from e in model.ESPECIALIDAD where e.VISIBLE == true select e).ToList();
            }
            else
            {
                datos = (from e in model.ESPECIALIDAD where e.NOMBRE.Contains(nombre) && e.VISIBLE == true select e).ToList();
            }

            return Json(datos);
        }

        public ActionResult agregarDoctor(string nombre, string apellido, string cedula, DateTime fechaNacimiento, string sexo, string direccion, string telefono, int[] especialidades)
        {
            Entities model = new Entities();
            DOCTOR doctor = new DOCTOR();
            doctor.NOMBRE = nombre;
            doctor.APELLIDO = apellido;
            doctor.CEDULA = cedula;
            doctor.FECHA_NACIMIENTO = fechaNacimiento;
            doctor.SEXO = sexo;
            doctor.DIRECCION = direccion;
            doctor.TELEFONO = telefono;
            doctor.VISIBLE = true;
            model.DOCTOR.Add(doctor);
            model.SaveChanges();
            foreach (int id in especialidades)
            {
                DOCTOR_ESPECIALIDAD de = new DOCTOR_ESPECIALIDAD();
                de.ID_DOCTOR = doctor.ID;
                de.ID_ESPECIALIDAD = id;
                de.VISIBLE = true;
                model.DOCTOR_ESPECIALIDAD.Add(de);
            }
            model.SaveChanges();
            return Json(doctor);
        }

        public ActionResult modificarDoctor(int id, string nombre, string apellido, string cedula, DateTime fechaNacimiento, string sexo, string direccion, string telefono, bool visible, int[] doctorEspecialidades = null, bool[] visibleDoctorEspecialidades = null, int[] especialidades = null)
        {
            Entities model = new Entities();
            var doctor = (from m in model.DOCTOR where m.ID == id select m).First();
            doctor.NOMBRE = nombre;
            doctor.APELLIDO = apellido;
            doctor.CEDULA = cedula;
            doctor.FECHA_NACIMIENTO = fechaNacimiento;
            doctor.SEXO = sexo;
            doctor.DIRECCION = direccion;
            doctor.TELEFONO = telefono;
            doctor.VISIBLE = visible;
            if (doctorEspecialidades != null)
            {
                for (int iX = 0; iX < doctorEspecialidades.Length; iX++)
                {
                    int iDE = doctorEspecialidades[iX];
                    DOCTOR_ESPECIALIDAD doctorEspecialidad = (from de in model.DOCTOR_ESPECIALIDAD where de.ID == iDE select de).First();
                    doctorEspecialidad.VISIBLE = visibleDoctorEspecialidades[iX];
                }
            }
            if (especialidades != null)
            {
                foreach (int especialidad in especialidades)
                {
                    DOCTOR_ESPECIALIDAD doctorEspecialidad = new DOCTOR_ESPECIALIDAD();
                    try
                    {
                        doctorEspecialidad = (from de in model.DOCTOR_ESPECIALIDAD where de.ID_DOCTOR == doctor.ID && de.ID_ESPECIALIDAD == especialidad select de).First();
                    }
                    catch (Exception ex)
                    { }
                    doctorEspecialidad.ID_DOCTOR = doctor.ID;
                    doctorEspecialidad.ID_ESPECIALIDAD = especialidad;
                    doctorEspecialidad.VISIBLE = true;
                    if (doctorEspecialidad.ID == 0)
                    {
                        model.DOCTOR_ESPECIALIDAD.Add(doctorEspecialidad);
                    }
                }
            }
            model.SaveChanges();
            return Json(doctor);
        }
    }
}

Hospital/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class HospitalController : Controller
    {
        // GET: Hospital
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult obtenerHospital(int id = 0)
        {
            Entities model = new Entities();
            var dato = (from h in model.HOSPITAL where h.ID == id select h).First();
            return Json(dato);
        }

        public ActionResult obtenerHospitales(string nombre = "")
        {
            Entities model = new Entities();
            if (nombre == "")
            {
                var datos = (from h in model.HOSPITAL where h.VISIBLE == true select h).ToList();
                return Json(datos);
            }
            else
            {
                var datos = (from h in model.HOSPITAL where h.NOMBRE.Contains(nombre) && h.VISIBLE == true select h).ToList();
                return Json(datos);
            }
        }

        public ActionResult agregarHospital(string nombre, string direccion)
        {
            Entities model = new Entities();
            HOSPITAL hospital = new HOSPITAL();
            hospital.NOMBRE = nombre;
            hospital.DIRECCION = direccion;
            hospital.VISIBLE = true;
            model.HOSPITAL.Add(hospital);
            model.SaveChanges();
            return Json(hospital);
        }

        public ActionResult modificarHospital(int id, string nombre, string direccion, bool visible)
        {
            Entities model = new Entities();
            var hospital = (from m in model.HOSPITAL where m.ID == id select m).First();
            hospital.NOMBRE = nombre;
            hospital.DIRECCION = direccion;
            hospital.VISIBLE = visible;
            model.SaveChanges();
            return Json(hospital);
        }
    }
}

Hospital/Views/Shared/_Footer.cshtml
        </div>
        <footer class="footer">
            <div class="container">
                <p class="text-muted">Place sticky footer content here.</p>
            </div>
        </footer>
    </body>
</html>

Hospital/Views/Shared/_Header.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hospital</title>
        <link href="@Url.Content("~/css/bootstrap.min.css")" rel="stylesheet">
        <link href="@Url.Content("~/css/style.css")" rel="stylesheet">
        <script src="@Url.Content("~/js/jquery-3.2.1.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/js/bootstrap.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/js/script.js")" type="text/javascript"></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Default")">Hospital</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrar<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Hospital")">Hospital</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Especialidad")">Especialidad</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Doctor")">Doctor</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Paciente")">Paciente</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Medicamento")">Medicamento</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Paciente<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Internado")">Internado</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Consulta")">Consulta</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reporte<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Reporte1</a>></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Reporte 2</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Reporte 3</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Reporte 4</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Reporte 5</a></li>
                        </ul>
                    </li>
                </ul>
                    </div>
            </div>
        </nav>
        <div class="container">